---
apiVersion: v1
kind: Secret
metadata:
  name: osp-compute1-bmc-secret
type: Opaque
data:
  username: YWRtaW4=
  password: cmVkaGF0
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
namespace: openshift-machine-api
metadata:
  name: osp-compute1
labels:
  app: openstack
  workload: compute
spec:
  online: false
  bootMACAddress: de:ad:be:ef:00:07
  bmc:
    address: ipmi://192.168.123.1:6237
    credentialsName: osp-compute1-bmc-secret
  rootDeviceHints:
    deviceName: /dev/vda